# Generated by Django 4.2.5 on 2023-09-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_application', '0002_alter_students_education_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'Student'), (3, 'Parent')], default=1, max_length=10),
        ),
    ]
