# Generated by Django 4.2.5 on 2023-09-18 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_application', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_number', models.CharField(max_length=20)),
                ('year_completed', models.PositiveIntegerField()),
                ('school_name', models.CharField(max_length=100)),
                ('results', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('education_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_application.educationlevel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_application.students')),
            ],
        ),
    ]
